version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    volumes:
      - .:/app # ホットローディングのために監視するディレクトリの指定
      - ./logs:/logs
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
  db:
    image: postgres:12.3-alpine
    container_name: db-container1
    ports:
      - "5432:5432"
    environment:
      TZ: "Asia/Tokyo"
      LANG: ja_JP.utf8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: test
